[workspace]
resolver = "2"

members = [
  "common",
  "flat_message",
  "flat_message_proc_macro",
  "examples",
  "benchmarks",
]

[workspace.lints.clippy]
module_inception = "allow"
new_without_default = "allow"
