[workspace]
resolver = "2"

members = [
  "common",
  "keyvaluestruct",
  "keyvaluestruct-proc-macro",
  "examples",
]

[workspace.lints.clippy]
module_inception = "allow"
new_without_default = "allow"
